sessionSecret: DAhxwoVlWpWSfeNIsJeFrb9dx19hwlSK
domain: "http://localhost:3000"

discord:
  clientId: "DISCORD_CLIENT_ID"
  clientSecret: "DISCORD_CLIENT_SECRET"
  callbackUrl: "http://localhost:3000/auth/discord/callback"

pterodactyl:
  panelUrl: "https://panel.example.com"
  apiKey: "APPLICATION_API_KEY"

# Connection string for your PostgreSQL database. This value can also be set
# via the DATABASE_URL environment variable.
databaseUrl: "postgresql://user:password@localhost:5432/niactyl"
