sessionSecret: DAhxwoVlWpWSfeNIsJeFrb9dx19hwlSK
domain: "http://localhost:3000"

discord:
  clientId: "DISCORD_CLIENT_ID"
  clientSecret: "DISCORD_CLIENT_SECRET"
  callbackUrl: "http://localhost:3000/auth/discord/callback"

pterodactyl:
  panelUrl: "https://panel.example.com"
  apiKey: "APPLICATION_API_KEY"

# PostgreSQL connection details. `DATABASE_URL` will be created from these
# values if it is not already set.
database:
  user: "user"
  password: "password"
  host: "localhost"
  port: 5432
  name: "niactyl"
